import Head from "next/head";
import Main from "../components/Main";
import Sidebar from "../components/Sidebar";

export default function Home() {
  return (
    <div className=" flex items-center justify-center h-screen bg-[#F9EAE5]">
      <Head>
        <title>About Me</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-[80%] h-[80%] flex rounded-xl overflow-hidden">
        <Sidebar />
        <Main />
      </main>
    </div>
  );
}
