import Head from "next/head";
import SkillsComponent from "../components/SkillsComponent";
import Sidebar from "../components/Sidebar";

export default function Skills() {
  return (
    <div className=" flex items-center justify-center h-screen bg-[#F9EAE5]">
      <Head>
        <title>Skills</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-[80%] h-[80%] flex rounded-xl overflow-hidden">
        <Sidebar />
        <SkillsComponent />
      </main>
    </div>
  );
}
